# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            КВЕСТ
tagline:          'Веб-вест'
description:      'Web-квест. Проблемне завдання
з елементами рольової гри'
url:              http://y5ywwiDKYdXoDDen.netlify.com
baseurl:          /

author:
  name:           'Th.Beregok'
  url:            https://beregok.github.com

paginate:         1

github:
  repo:           https://github.com/beregok/y5ywwiDKYdXoDDen
